### ISSUE TITLE
Support for Symfony 2.6.*?

### ISSUE THREAD

**Issue by frankadrian** [brunschgi/TerrificComposerBundle#10]
Are you planing of updating to later versions of symfony than 2.2?

**Comment by brunschgi** [comment]
Hi Frank

Unfortunately not. We are not using the TerrificComposerBundle anymore at our company (we switched to Node). Therefore the bundle is not going to be updated in the future.

Sorry for the bad news.

Cheers
Remo

**Comment by frankadrian** [comment]
Cool, Thanks for the update. Great project by the way!! Big Thanks.
